# Generated by Django 5.2.17 on 2026-09-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('repo_url', models.URLField(help_text='Repository mapping link (e.g. GitHub, GitLab)', max_length=500)),
                ('github_repo_name', models.CharField(blank=True, default='', help_text='Format: owner/repo', max_length=150)),
                ('demo_url', models.URLField(blank=True, default='', max_length=500)),
                ('project_type', models.CharField(choices=[('WEB', 'Web Application'), ('API', 'REST / GraphQL API'), ('MOBILE', 'Mobile App'), ('AI_ML', 'AI & Machine Learning'), ('CLI', 'CLI Tool / Library'), ('OPEN_SOURCE', 'Open Source Package'), ('OTHER', 'Other')], db_index=True, default='WEB', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags e.g. ["django", "postgres", "jwt"]')),
                ('stars_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='accounts.skill')),
            ],
            options={
                'ordering': ['-stars_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
